<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>NewTennisOutput</groupId>
    <artifactId>NewTennisOutput</artifactId>
    <version>2.2</version>
    <packaging>war</packaging>
    <name>NewTennisOutput</name>

    <properties>
        <java.version>17</java.version>
        <spring.version>6.1.8</spring.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- ========================= -->
        <!-- Your Library -->
        <!-- ========================= -->

        <dependency>
            <groupId>com.tennis</groupId>
            <artifactId>NewTennisLibrary</artifactId>
            <version>2.4</version>
        </dependency>

        <!-- ========================= -->
        <!-- Servlet -->
        <!-- ========================= -->

		<dependency>
		    <groupId>commons-beanutils</groupId>
		    <artifactId>commons-beanutils</artifactId>
		    <version>1.9.4</version>
		</dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- ========================= -->
        <!-- JSP -->
        <!-- ========================= -->

        <dependency>
            <groupId>jakarta.servlet.jsp</groupId>
            <artifactId>jakarta.servlet.jsp-api</artifactId>
            <version>3.1.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- ========================= -->
        <!-- JSTL -->
        <!-- ========================= -->

        <dependency>
            <groupId>jakarta.servlet.jsp.jstl</groupId>
            <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
            <version>3.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.web</groupId>
            <artifactId>jakarta.servlet.jsp.jstl</artifactId>
            <version>3.0.1</version>
        </dependency>

        <!-- ========================= -->
        <!-- Spring Web -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>${spring.version}</version>
        </dependency>

        <!-- ========================= -->
        <!-- Spring Security -->
        <!-- ========================= -->

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
            <version>6.2.4</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
            <version>6.2.4</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-taglibs</artifactId>
            <version>6.2.4</version>
        </dependency>

        <!-- ========================= -->
        <!-- Frontend -->
        <!-- ========================= -->

		<dependency>
		    <groupId>org.webjars.npm</groupId>
		    <artifactId>html2canvas</artifactId>
		    <version>1.4.1</version>
		</dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>bootstrap</artifactId>
            <version>5.3.3</version>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>jquery</artifactId>
            <version>3.7.1</version>
        </dependency>

		<dependency>
		    <groupId>org.webjars</groupId>
		    <artifactId>font-awesome</artifactId>
		    <version>6.5.1</version>
		</dependency>

        <dependency>
            <groupId>org.webjars.npm</groupId>
            <artifactId>select2</artifactId>
            <version>4.1.0-rc.0</version>
        </dependency>

    </dependencies>

    <build>

        <sourceDirectory>src</sourceDirectory>

        <finalName>NewTennis</finalName>

        <plugins>

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>

                <configuration>

                    <source>${java.version}</source>
                    <target>${java.version}</target>

                </configuration>

            </plugin>

            <plugin>

                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>

                <configuration>
                    <warSourceDirectory>WebContent</warSourceDirectory>
                </configuration>

            </plugin>

        </plugins>

    </build>

</project>